#!/bin/bash

# global settings
resolution="1366x768"
fps="30"
quality="0"
preset="superfast"
codec="libx264rgb"
threads="2"
scale="1280x720"
# tune="zerolatency"

# actual ffmpeg command
ffmpeg \
\
-threads $threads \
\
-f x11grab \
-video_size $resolution \
-framerate $fps \
-thread_queue_size 1024 \
-i $DISPLAY \
\
-f pulse \
-i default \
\
-vf scale=$scale \
-c:v $codec -g $fps \
-preset $preset \
-r $fps \
\
$1

# a few things to note:
# I have no idea what the -g $fps does, but im keeping it there incase something breaks 
# doing -framerate and -r gives me a good quality and consistency with a medium load average
# doing -r first then -framerate gives me a fever dream with high framerates, high load averages and the most fluctuating movement I have seen in minecraft, or a recording in general

# Additional options that might be valid now or in the future
#-af acontrast \
#-tune $tune \
# -hwaccel auto \
#-crf $quality \
#-b:v 4M \
#-minrate 4M \
#
# -af acompressor=threshold=0.089:ratio=9:attack=200:release=1000 \

# -f pulse -i default \
