#!/bin/bash

# global settings
resolution="1920x1080"
fps="24"
quality="0"
preset="medium"
codec="libx264rgb"
threads="2"
scale="1280x720"
# tune="zerolatency"

# actual ffmpeg command
ffmpeg \
\
\
-threads $threads \
\
-f x11grab \
-video_size $resolution \
-framerate $fps -g $fps\
-i :0.0 \
\
\
-f pulse -i default \
-af acontrast=contrast=0 \
\
\
\
-vf scale=$scale \
-c:v $codec \
-preset $preset \
-r $fps \
\
\
\
$1

# a few things to note:
# I have no idea what the -g $fps does, but im keeping it there incase something breaks 
# doing -framerate and -r gives me a good quality and consistency with a medium load average
# doing -r first then -framerate gives me a fever dream with high framerates, high load averages and the most fluctuating movement I have seen in minecraft

# Additional options that might be valid now or in the future
#-af acontrast \
#-tune $tune \
# -hwaccel auto \
#-crf $quality \
#-b:v 4M \
#-minrate 4M \
#
# -af acompressor=threshold=0.089:ratio=9:attack=200:release=1000 \
# "sftp://khail:pki7692gi@192.168.2.2/home/khail/Videos/$1"
